# Generated by Django 5.0.7 on 2026-06-12 14:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('etl_logs', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='etllog',
            name='status',
            field=models.CharField(choices=[('SUCCESS', 'SUCCESS'), ('FAILED', 'FAILED')], max_length=20),
        ),
    ]
