# Generated by Django 5.0.7 on 2026-06-12 09:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='remote',
            field=models.BooleanField(default=False),
        ),
    ]
